language: elixir
elixir: 1.2.3
notifications:
  recipients:
    - blsymph@gmail.com
otp_release:
  - 18.0
# to run on faster container-based infastructure
sudo: false
env:
  - MIX_ENV=test
before_script:
  - mix deps.get
script: mix test
