language: erlang
notifications:
    recipients:
        - blsymph@gmail.com
otp_release:
    - R16B
before_install:
    - git clone https://github.com/elixir-lang/elixir
    - cd elixir && git checkout v1.0.0 && make && cd ..
before_script: "export PATH=`pwd`/elixir/bin:$PATH"
script: "MIX_ENV=test mix do deps.get, test"
