language: elixir
elixir: 1.3.4
notifications:
  recipients:
    - blsymph@gmail.com
otp_release:
  - 19.0
# to run on faster container-based infastructure
sudo: false
env:
  - MIX_ENV=test
before_script:
  - mix deps.get
script: mix test
